apiVersion: v1
kind: Pod
metadata:
 name: user-pod
 labels:
   app: user
spec:
  app: user-api
    containers:
        - name: user-api
          image: gcr.io/lloyds-hackathon-team-4/user-api:v1.0
          ports:
            - containerPort: 8080